using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;
namespace LedgerDesk;
public sealed class CategoryChoice(string name,string icon):System.ComponentModel.INotifyPropertyChanged{bool selected;public string Name{get;}=name;public string Icon{get;}=icon;public bool IsSelected{get=>selected;set{if(selected==value)return;selected=value;Changed();Changed(nameof(Background));Changed(nameof(Border));Changed(nameof(IconBackground));Changed(nameof(IconBrush));Changed(nameof(SelectedLabel));}}public Brush Background=>new SolidColorBrush(IsSelected?Color.FromRgb(232,246,239):Colors.White);public Brush Border=>new SolidColorBrush(IsSelected?Color.FromRgb(23,107,81):Color.FromRgb(226,234,230));public Brush IconBackground=>new SolidColorBrush(IsSelected?Color.FromRgb(23,107,81):Color.FromRgb(235,245,240));public Brush IconBrush=>new SolidColorBrush(IsSelected?Colors.White:Color.FromRgb(23,107,81));public string SelectedLabel=>IsSelected?"✓ 已选择":"";public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;void Changed([System.Runtime.CompilerServices.CallerMemberName]string? n=null)=>PropertyChanged?.Invoke(this,new(n));}
public partial class EntryDialogPro:Window
{
 readonly Dictionary<string,List<string>> cats;readonly List<CategoryChoice> expenseChoices=[],incomeChoices=[];string type="支出",category="餐饮",expenseKind="";public Entry Result{get;private set;}
 public EntryDialogPro(Dictionary<string,List<string>> categories,Entry? source=null){InitializeComponent();ApplyRoundedInputs();cats=categories;Result=source is null?new Entry():Clone(source);expenseChoices=Choices(categories["支出"]);incomeChoices=Choices(categories["收入"]);ExpenseCategories.ItemsSource=expenseChoices;IncomeCategories.ItemsSource=incomeChoices;AccountBox.ItemsSource=new[]{"微信","支付宝","银行卡","现金","其他"};StatusBox.ItemsSource=new[]{"进行中","已结清"};Loaded+=(_,_)=>Fill();}
 void ApplyRoundedInputs(){var style=Application.Current.TryFindResource(typeof(TextBox)) as Style;if(style==null)return;foreach(var box in Find<TextBox>(this))box.Style=style;}
 static IEnumerable<T> Find<T>(DependencyObject root)where T:DependencyObject{for(int i=0;i<VisualTreeHelper.GetChildrenCount(root);i++){var child=VisualTreeHelper.GetChild(root,i);if(child is T hit)yield return hit;foreach(var nested in Find<T>(child))yield return nested;}}
 static Entry Clone(Entry e)=>new(){Id=e.Id,Type=e.Type,Amount=e.Amount,Date=e.Date,Category=e.Category,Account=e.Account,Party=e.Party,Status=e.Status,DueDate=e.DueDate,Repaid=e.Repaid,Note=e.Note,Project=e.Project,Reference=e.Reference,Rate=e.Rate,Custom=e.Custom};
 static List<CategoryChoice> Choices(IEnumerable<string> cs)=>cs.Select(c=>new CategoryChoice(c,c switch{"餐饮"=>"utensils","购物"=>"shopping-bag","交通"=>"car-taxi-front","住房"=>"house","医疗"=>"heart-pulse","娱乐"=>"clapperboard","教育"=>"graduation-cap","工资" or "奖金" or "副业"=>"circle-dollar-sign",_=>"wallet-cards"})).ToList();
 void Fill(){DateBox.SelectedDate=Result.Date;AmountBox.Text=Result.Amount==0?"":Result.Amount.ToString();AccountBox.SelectedItem=Result.Account;NoteBox.Text=Result.Note;PartyBox.Text=Result.Party;StatusBox.SelectedItem=Result.Status;ProjectBox.Text=Result.Project;ReferenceBox.Text=Result.Reference;DueDateBox.SelectedDate=Result.DueDate;RepaidBox.Text=Result.Repaid.ToString();category=Result.Category;expenseKind=ExpenseClassification.Kind(Result) is "生活消费" or "大额支出" ? ExpenseClassification.Kind(Result) : "";ShowType(Result.Type);UpdateCategorySelection();}
 void ShowType(string t){type=t;bool exp=t=="支出",inc=t=="收入",fund=!exp&&!inc;ExpensePage.Visibility=exp?Visibility.Visible:Visibility.Collapsed;IncomePage.Visibility=inc?Visibility.Visible:Visibility.Collapsed;FundsPage.Visibility=fund?Visibility.Visible:Visibility.Collapsed;FlowFields.Visibility=fund?Visibility.Visible:Visibility.Collapsed;SetTab(ExpenseTab,exp);SetTab(IncomeTab,inc);SetTab(FundsTab,fund);if(exp||inc)UpdateCategorySelection();if(exp)SetExpenseKindButtons();if(fund){FundCategory.ItemsSource=cats[t];FundCategory.SelectedItem=category;if(FundCategory.SelectedIndex<0)FundCategory.SelectedIndex=0;SetFundButtons();}}
 static void SetTab(Button b,bool active){b.Background=new SolidColorBrush(active?Color.FromRgb(23,107,81):Colors.Transparent);b.Foreground=new SolidColorBrush(active?Colors.White:Color.FromRgb(48,68,60));}void SetFundButtons(){foreach(var b in new[]{BorrowTab,LendTab,InvestTab}){bool on=(string)b.Tag==type;b.Background=new SolidColorBrush(on?Color.FromRgb(230,244,238):Color.FromRgb(244,247,245));b.Foreground=new SolidColorBrush(on?Color.FromRgb(23,107,81):Color.FromRgb(63,78,71));}}
 void ExpenseKind_Click(object s,RoutedEventArgs e){expenseKind=(string)((Button)s).Tag;SetExpenseKindButtons();}void SetExpenseKindButtons(){foreach(var b in new[]{LivingExpenseButton,LargeExpenseButton}){bool on=(string)b.Tag==expenseKind;b.Background=new SolidColorBrush(on?Color.FromRgb(23,107,81):Color.FromRgb(241,245,243));b.Foreground=new SolidColorBrush(on?Colors.White:Color.FromRgb(48,68,60));}}void ExpenseTab_Click(object s,RoutedEventArgs e){category=cats["支出"].First();ShowType("支出");}void IncomeTab_Click(object s,RoutedEventArgs e){category=cats["收入"].First();ShowType("收入");}void FundsTab_Click(object s,RoutedEventArgs e){category=cats["借入"].First();ShowType("借入");}void FundType_Click(object s,RoutedEventArgs e){type=(string)((Button)s).Tag;category=cats[type].First();ShowType(type);}void Category_Click(object s,RoutedEventArgs e){if((s as FrameworkElement)?.DataContext is CategoryChoice c){category=c.Name;UpdateCategorySelection();}}void UpdateCategorySelection(){foreach(var c in expenseChoices.Concat(incomeChoices))c.IsSelected=c.Name==category;}
 void Save_Click(object s,RoutedEventArgs e){if(type=="支出"&&expenseKind.Length==0){MessageBox.Show("请选择生活消费或大额支出。","简账");return;}if(!decimal.TryParse(AmountBox.Text,out var amount)||amount<=0){MessageBox.Show("请输入正确金额。","简账");return;}decimal.TryParse(RepaidBox.Text,out var repaid);Result.Type=type;Result.Category=type is "支出" or "收入"?category:(FundCategory.SelectedItem?.ToString()??category);Result.Amount=amount;if(type=="支出")Result.Custom=expenseKind;Result.Date=DateBox.SelectedDate??DateTime.Today;Result.Account=AccountBox.SelectedItem?.ToString()??"其他";Result.Note=NoteBox.Text.Trim();Result.Party=PartyBox.Text.Trim();Result.Status=type is "支出" or "收入"?"已结清":StatusBox.SelectedItem?.ToString()??"进行中";Result.Project=ProjectBox.Text.Trim();Result.Reference=ReferenceBox.Text.Trim();Result.DueDate=DueDateBox.SelectedDate;Result.Repaid=repaid;DialogResult=true;}void Drag_Click(object s,MouseButtonEventArgs e){if(e.ChangedButton==MouseButton.Left)DragMove();}void Cancel_Click(object s,RoutedEventArgs e)=>DialogResult=false;
}
