using System.Globalization;using System.IO;using System.Text.Json;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Animation;
namespace LedgerDesk;
public static class MonthlyDashboard
{
 static bool attached;
 public static void Attach(ShellWindow w){if(attached)return;attached=true;if((w.FindName("DashboardPage") as ScrollViewer)?.Content is not StackPanel root)return;var records=Read().Records;var grid=new Grid{Height=300,Margin=new Thickness(0,0,0,18)};grid.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(16)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(1.35,GridUnitType.Star)});var ring=new AnimatedMonthRing{Records=records};var months=Enumerable.Range(0,24).Select(i=>new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(-i)).ToList();var picker=new ComboBox{Width=118,ItemsSource=months,SelectedIndex=0,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0)};picker.ItemTemplate=MonthTemplate();picker.SelectionChanged+=(_,_)=>{if(picker.SelectedItem is DateTime m)ring.ShowMonth(m);};var pie=ChartCard("消费构成",ring,picker);var bars=ChartCard("近 6 个月收支对比",new MonthlyBarChart{Records=records},null);Grid.SetColumn(bars,2);grid.Children.Add(pie);grid.Children.Add(bars);root.Children.Insert(Math.Min(1,root.Children.Count),grid);ring.ShowMonth(months[0]);}
 static DataTemplate MonthTemplate(){var f=new FrameworkElementFactory(typeof(TextBlock));f.SetBinding(TextBlock.TextProperty,new System.Windows.Data.Binding("."){StringFormat="{0:yyyy年M月}"});return new DataTemplate{VisualTree=f};}
 static Border ChartCard(string title,FrameworkElement chart,FrameworkElement? action){var header=new DockPanel{Margin=new Thickness(0,0,0,8)};header.Children.Add(new TextBlock{Text=title,FontSize=15,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center});if(action!=null){DockPanel.SetDock(action,Dock.Right);header.Children.Add(action);}var g=new Grid();g.RowDefinitions.Add(new(){Height=GridLength.Auto});g.RowDefinitions.Add(new(){Height=new GridLength(1,GridUnitType.Star)});Grid.SetRow(chart,1);g.Children.Add(header);g.Children.Add(chart);return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(14),Padding=new Thickness(18),Child=g};}
 static LedgerData Read(){try{var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"简账","ledger.json");return File.Exists(f)?JsonSerializer.Deserialize<LedgerData>(File.ReadAllText(f))??new():new();}catch{return new();}}
}
public class AnimatedMonthRing:FrameworkElement
{
 public List<Entry> Records{get;set;}=[];DateTime month=DateTime.Today;public static readonly DependencyProperty ProgressProperty=DependencyProperty.Register(nameof(Progress),typeof(double),typeof(AnimatedMonthRing),new FrameworkPropertyMetadata(1d,FrameworkPropertyMetadataOptions.AffectsRender));public double Progress{get=>(double)GetValue(ProgressProperty);set=>SetValue(ProgressProperty,value);}readonly Color[] colors=[Color.FromRgb(42,139,102),Color.FromRgb(234,177,69),Color.FromRgb(208,91,86),Color.FromRgb(72,123,180),Color.FromRgb(142,99,176),Color.FromRgb(72,164,168),Color.FromRgb(230,132,69)];
 public void ShowMonth(DateTime value){month=value;BeginAnimation(ProgressProperty,new DoubleAnimation(0,1,TimeSpan.FromMilliseconds(720)){EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});InvalidateVisual();}
 protected override void OnRender(DrawingContext dc){base.OnRender(dc);var rows=Records.Where(x=>x.Type=="支出"&&x.Date.Year==month.Year&&x.Date.Month==month.Month).GroupBy(x=>x.Category).Select(g=>(name:g.Key,value:g.Sum(x=>x.Amount))).OrderByDescending(x=>x.value).Take(7).ToList();var total=rows.Sum(x=>x.value);if(total<=0){T(dc,$"{month:M月}暂无支出",new Point(ActualWidth/2,ActualHeight/2-8),12,TextAlignment.Center,Brushes.Gray);return;}double ringSize=Math.Min(ActualHeight-20,ActualWidth*.48);double cx=ringSize/2+4;double cy=ActualHeight/2;double r=ringSize*.35;double thickness=Math.Max(16,r*.28);double start=-135;double visible=360*Math.Clamp(Progress,0,1);double used=0;for(int i=0;i<rows.Count&&used<visible;i++){double full=(double)(rows[i].value/total)*360;double sweep=Math.Min(full,visible-used);DrawArc(dc,new Point(cx,cy),r,start+used,sweep,new SolidColorBrush(colors[i%colors.Length]),thickness);used+=full;}T(dc,$"¥{total:N0}",new Point(cx,cy-12),15,TextAlignment.Center,Brushes.Black);T(dc,$"{month:yyyy年M月}",new Point(cx,cy+10),10,TextAlignment.Center,Brushes.Gray);for(int i=0;i<rows.Count;i++){double y=12+i*27;double x=ringSize+18;dc.DrawRoundedRectangle(new SolidColorBrush(colors[i%colors.Length]),null,new Rect(x,y+4,9,9),3,3);T(dc,rows[i].name,new Point(x+16,y),11,TextAlignment.Left,Brushes.Black);T(dc,$"{rows[i].value/total:P0}",new Point(ActualWidth-4,y),11,TextAlignment.Right,Brushes.DimGray);}}
 static void DrawArc(DrawingContext dc,Point c,double r,double start,double sweep,Brush brush,double width){if(sweep<=.01)return;double A(double x)=>x*Math.PI/180;var p1=new Point(c.X+r*Math.Cos(A(start)),c.Y+r*Math.Sin(A(start)));var p2=new Point(c.X+r*Math.Cos(A(start+sweep)),c.Y+r*Math.Sin(A(start+sweep)));var g=new StreamGeometry();using(var x=g.Open()){x.BeginFigure(p1,false,false);x.ArcTo(p2,new Size(r,r),0,sweep>180,SweepDirection.Clockwise,true,false);}dc.DrawGeometry(null,new Pen(brush,width){StartLineCap=PenLineCap.Round,EndLineCap=PenLineCap.Round},g);}internal static void T(DrawingContext d,string s,Point p,double size,TextAlignment align,Brush brush){var f=new FormattedText(s,CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei"),size,brush,1.25){TextAlignment=align};d.DrawText(f,p);}
}
public class MonthlyBarChart:FrameworkElement
{
 public List<Entry> Records{get;set;}=[];protected override void OnRender(DrawingContext dc){base.OnRender(dc);var ms=Enumerable.Range(0,6).Select(i=>new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(i-5)).ToList();var vals=ms.Select(m=>(m,inc:Records.Where(x=>x.Type=="收入"&&x.Date.Year==m.Year&&x.Date.Month==m.Month).Sum(x=>x.Amount),exp:Records.Where(x=>x.Type=="支出"&&x.Date.Year==m.Year&&x.Date.Month==m.Month).Sum(x=>x.Amount))).ToList();decimal max=Math.Max(1,vals.SelectMany(x=>new[]{x.inc,x.exp}).Max());double left=30;double top=20;double bottom=30;double w=(ActualWidth-left-8)/6;double area=ActualHeight-top-bottom;dc.DrawLine(new Pen(new SolidColorBrush(Color.FromRgb(229,236,232)),1),new Point(left,top+area),new Point(ActualWidth-5,top+area));for(int i=0;i<6;i++){double x=left+i*w+w*.18;double a=(double)(vals[i].inc/max)*area*.86;double b=(double)(vals[i].exp/max)*area*.86;dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(68,155,119)),null,new Rect(x,top+area-a,w*.24,a),3,3);dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(218,103,95)),null,new Rect(x+w*.3,top+area-b,w*.24,b),3,3);AnimatedMonthRing.T(dc,$"{vals[i].m.Month}月",new Point(x+w*.26,top+area+8),10,TextAlignment.Center,Brushes.Gray);}dc.DrawEllipse(new SolidColorBrush(Color.FromRgb(68,155,119)),null,new Point(left+5,7),4,4);AnimatedMonthRing.T(dc,"收入",new Point(left+13,1),10,TextAlignment.Left,Brushes.Gray);dc.DrawEllipse(new SolidColorBrush(Color.FromRgb(218,103,95)),null,new Point(left+65,7),4,4);AnimatedMonthRing.T(dc,"支出",new Point(left+73,1),10,TextAlignment.Left,Brushes.Gray);}
}
