using System.Globalization;using System.IO;using System.Text.Json;using System.Windows;using System.Windows.Controls;using System.Windows.Media;using System.Windows.Media.Animation;
namespace LedgerDesk;
public static class MonthlyDashboard
{
 static bool attached;static List<Entry> latest=[];static AnimatedMonthRing? ring;static HorizontalComparisonChart? comparison;
 public static void UpdateRecords(IEnumerable<Entry> records){latest=records.Select(Clone).ToList();ring?.SetRecords(latest);comparison?.SetRecords(latest);}
 public static void Attach(ShellWindow w){if(attached)return;attached=true;if((w.FindName("DashboardPage")as ScrollViewer)?.Content is not StackPanel root)return;if(latest.Count==0)latest=Read().Records;ring=new AnimatedMonthRing();ring.SetRecords(latest);comparison=new HorizontalComparisonChart();comparison.SetRecords(latest);var grid=new Grid{Height=330,Margin=new Thickness(0,0,0,18)};grid.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(16)});grid.ColumnDefinitions.Add(new(){Width=new GridLength(1.4,GridUnitType.Star)});var months=Enumerable.Range(0,36).Select(i=>new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(-i)).ToList();var monthPicker=Picker(months,118,"{0:yyyy年M月}");monthPicker.SelectedIndex=0;monthPicker.SelectionChanged+=(_,_)=>{if(monthPicker.SelectedItem is DateTime m)ring.ShowMonth(m);};var modes=new[]{"月度对比","年度对比"};var modePicker=Picker(modes,105,null);modePicker.SelectionChanged+=(_,_)=>comparison.Mode=modePicker.SelectedIndex==1?ComparisonMode.Year:ComparisonMode.Month;modePicker.SelectedIndex=0;var pie=Card("单月消费构成",ring,monthPicker);var bars=Card("收入 / 支出横向对比",comparison,modePicker);Grid.SetColumn(bars,2);grid.Children.Add(pie);grid.Children.Add(bars);root.Children.Insert(Math.Min(1,root.Children.Count),grid);ring.ShowMonth(months[0],false);}
 static ComboBox Picker(System.Collections.IEnumerable items,double width,string? format){var p=new ComboBox{Width=width,ItemsSource=items,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0)};if(format!=null){var f=new FrameworkElementFactory(typeof(TextBlock));f.SetBinding(TextBlock.TextProperty,new System.Windows.Data.Binding("."){StringFormat=format});p.ItemTemplate=new DataTemplate{VisualTree=f};}return p;}
 static Border Card(string title,FrameworkElement chart,FrameworkElement action){var header=new DockPanel{Margin=new Thickness(0,0,0,8)};var label=new TextBlock{Text=title,FontSize=15,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center};DockPanel.SetDock(action,Dock.Right);header.Children.Add(action);header.Children.Add(label);var g=new Grid();g.RowDefinitions.Add(new(){Height=GridLength.Auto});g.RowDefinitions.Add(new(){Height=new GridLength(1,GridUnitType.Star)});Grid.SetRow(chart,1);g.Children.Add(header);g.Children.Add(chart);return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(14),Padding=new Thickness(18),Child=g};}
 static LedgerData Read(){try{var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"简账","ledger.json");return File.Exists(f)?JsonSerializer.Deserialize<LedgerData>(File.ReadAllText(f))??new():new();}catch{return new();}}static Entry Clone(Entry e)=>new(){Id=e.Id,Type=e.Type,Amount=e.Amount,Date=e.Date,Category=e.Category,Account=e.Account,Party=e.Party,Status=e.Status,DueDate=e.DueDate,Repaid=e.Repaid,Note=e.Note,Project=e.Project,Reference=e.Reference,Rate=e.Rate,Custom=e.Custom};
}
public class AnimatedMonthRing:FrameworkElement
{
 Dictionary<(int year,int month,string category),decimal> expenseCache=[];DateTime month=DateTime.Today;public static readonly DependencyProperty ProgressProperty=DependencyProperty.Register(nameof(Progress),typeof(double),typeof(AnimatedMonthRing),new FrameworkPropertyMetadata(1d,FrameworkPropertyMetadataOptions.AffectsRender));public double Progress{get=>(double)GetValue(ProgressProperty);set=>SetValue(ProgressProperty,value);}readonly Color[] colors=[Color.FromRgb(42,139,102),Color.FromRgb(234,177,69),Color.FromRgb(208,91,86),Color.FromRgb(72,123,180),Color.FromRgb(142,99,176),Color.FromRgb(72,164,168),Color.FromRgb(230,132,69)];
 public void SetRecords(IEnumerable<Entry> value){expenseCache=value.Where(x=>x.Type=="支出").GroupBy(x=>(x.Date.Year,x.Date.Month,x.Category)).ToDictionary(g=>g.Key,g=>g.Sum(x=>x.Amount));InvalidateVisual();}public void ShowMonth(DateTime value,bool animate=true){month=value;if(animate)BeginAnimation(ProgressProperty,new DoubleAnimation(0,1,TimeSpan.FromMilliseconds(720)){EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});else{BeginAnimation(ProgressProperty,null);Progress=1;}InvalidateVisual();}
 protected override void OnRender(DrawingContext dc){base.OnRender(dc);var rows=expenseCache.Where(x=>x.Key.year==month.Year&&x.Key.month==month.Month).Select(x=>(name:x.Key.category,value:x.Value)).OrderByDescending(x=>x.value).Take(7).ToList();var total=rows.Sum(x=>x.value);if(total<=0){Text(dc,$"{month:yyyy年M月}暂无支出",new Point(ActualWidth/2,ActualHeight/2-8),12,TextAlignment.Center,Brushes.Gray);return;}double ringSize=Math.Min(ActualHeight-20,ActualWidth*.48),cx=ringSize/2+4,cy=ActualHeight/2,r=ringSize*.35,thickness=Math.Max(16,r*.28),start=-135,visible=360*Math.Clamp(Progress,0,1),used=0;for(int i=0;i<rows.Count&&used<visible;i++){double full=(double)(rows[i].value/total)*360,sweep=Math.Min(full,visible-used);Arc(dc,new Point(cx,cy),r,start+used,sweep,new SolidColorBrush(colors[i%colors.Length]),thickness);used+=full;}Text(dc,$"¥{total:N0}",new Point(cx,cy-12),15,TextAlignment.Center,Brushes.Black);Text(dc,$"{month:yyyy年M月}",new Point(cx,cy+10),10,TextAlignment.Center,Brushes.Gray);for(int i=0;i<rows.Count;i++){double y=12+i*27,x=ringSize+18;dc.DrawRoundedRectangle(new SolidColorBrush(colors[i%colors.Length]),null,new Rect(x,y+4,9,9),3,3);Text(dc,rows[i].name,new Point(x+16,y),11,TextAlignment.Left,Brushes.Black);Text(dc,$"{rows[i].value/total:P0}",new Point(ActualWidth-4,y),11,TextAlignment.Right,Brushes.DimGray);}}
 static void Arc(DrawingContext dc,Point c,double r,double start,double sweep,Brush brush,double width){if(sweep<=.01)return;double A(double x)=>x*Math.PI/180;var p1=new Point(c.X+r*Math.Cos(A(start)),c.Y+r*Math.Sin(A(start)));var p2=new Point(c.X+r*Math.Cos(A(start+sweep)),c.Y+r*Math.Sin(A(start+sweep)));var g=new StreamGeometry();using(var x=g.Open()){x.BeginFigure(p1,false,false);x.ArcTo(p2,new Size(r,r),0,sweep>180,SweepDirection.Clockwise,true,false);}dc.DrawGeometry(null,new Pen(brush,width){StartLineCap=PenLineCap.Round,EndLineCap=PenLineCap.Round},g);}internal static void Text(DrawingContext d,string s,Point p,double size,TextAlignment align,Brush brush){var f=new FormattedText(s,CultureInfo.GetCultureInfo("zh-CN"),FlowDirection.LeftToRight,new Typeface("Microsoft YaHei"),size,brush,1.25){TextAlignment=align};d.DrawText(f,p);}
}
public enum ComparisonMode{Month,Year}
public class HorizontalComparisonChart:FrameworkElement
{
 Dictionary<(string type,int year,int month),decimal> monthCache=[];Dictionary<(string type,int year),decimal> yearCache=[];ComparisonMode mode;public ComparisonMode Mode{get=>mode;set{mode=value;InvalidateVisual();}}public void SetRecords(IEnumerable<Entry> value){var rows=value.Where(x=>x.Type is "收入" or "支出").ToList();monthCache=rows.GroupBy(x=>(x.Type,x.Date.Year,x.Date.Month)).ToDictionary(g=>g.Key,g=>g.Sum(x=>x.Amount));yearCache=rows.GroupBy(x=>(x.Type,x.Date.Year)).ToDictionary(g=>g.Key,g=>g.Sum(x=>x.Amount));InvalidateVisual();}
 protected override void OnRender(DrawingContext dc){base.OnRender(dc);var rows=Mode==ComparisonMode.Month?Enumerable.Range(0,6).Select(i=>new DateTime(DateTime.Today.Year,DateTime.Today.Month,1).AddMonths(i-5)).Select(d=>(label:$"{d.Month}月",inc:Sum("收入",d.Year,d.Month),exp:Sum("支出",d.Year,d.Month))).ToList():Enumerable.Range(0,5).Select(i=>DateTime.Today.Year+i-4).Select(y=>(label:$"{y}年",inc:Sum("收入",y,null),exp:Sum("支出",y,null))).ToList();decimal max=Math.Max(1,rows.SelectMany(x=>new[]{x.inc,x.exp}).Max());double labelW=54,right=58,top=18,rowH=(ActualHeight-top-8)/rows.Count;for(int i=0;i<rows.Count;i++){double y=top+i*rowH;AnimatedMonthRing.Text(dc,rows[i].label,new Point(0,y+rowH*.34),10,TextAlignment.Left,Brushes.DimGray);DrawBar(dc,labelW,y+4,rows[i].inc,max,ActualWidth-labelW-right,rowH*.28,Color.FromRgb(64,151,115));DrawBar(dc,labelW,y+rowH*.46,rows[i].exp,max,ActualWidth-labelW-right,rowH*.28,Color.FromRgb(214,94,87));AnimatedMonthRing.Text(dc,$"¥{Math.Max(rows[i].inc,rows[i].exp):N0}",new Point(ActualWidth-2,y+rowH*.34),9,TextAlignment.Right,Brushes.Gray);}dc.DrawEllipse(new SolidColorBrush(Color.FromRgb(64,151,115)),null,new Point(labelW,6),4,4);AnimatedMonthRing.Text(dc,"收入",new Point(labelW+9,0),10,TextAlignment.Left,Brushes.Gray);dc.DrawEllipse(new SolidColorBrush(Color.FromRgb(214,94,87)),null,new Point(labelW+60,6),4,4);AnimatedMonthRing.Text(dc,"支出",new Point(labelW+69,0),10,TextAlignment.Left,Brushes.Gray);}
 decimal Sum(string type,int year,int? month)=>month.HasValue?(monthCache.TryGetValue((type,year,month.Value),out var monthly)?monthly:0):(yearCache.TryGetValue((type,year),out var yearly)?yearly:0);static void DrawBar(DrawingContext dc,double x,double y,decimal value,decimal max,double width,double height,Color color){double w=(double)(value/max)*width;dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(239,243,241)),null,new Rect(x,y,width,height),height/2,height/2);if(w>0)dc.DrawRoundedRectangle(new SolidColorBrush(color),null,new Rect(x,y,w,height),height/2,height/2);}
}
