using Microsoft.Win32;using System.Globalization;using System.IO;using System.Text;using System.Text.Json;using System.Windows;using System.Windows.Controls;using System.Windows.Controls.Primitives;using System.Windows.Input;using System.Windows.Media;
namespace LedgerDesk;
public partial class ShellWindow:Window
{
 readonly string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"简账");string FileName=>Path.Combine(dir,"ledger.json");LedgerData data=new();TextBlock FilterCount=new(),FilterMoney=new(),OpenFunds=new();
 public ShellWindow(){InitializeComponent();Load();SubTitle.Text=DateTime.Today.ToString("yyyy年M月d日 dddd",new CultureInfo("zh-CN"));TypeFilter.ItemsSource=new[]{"全部类型","收入","支出","借入","借出","投资中"};TypeFilter.SelectedIndex=0;EnhanceRecords();Refresh();}
 void EnhanceRecords(){var old=RecordsPage.Children.OfType<DockPanel>().FirstOrDefault(x=>Grid.GetRow(x)==0);if(old==null)return;RecordsPage.Children.Remove(old);var stack=new StackPanel{Margin=new Thickness(0,0,0,14)};Grid.SetRow(stack,0);var stats=new UniformGrid{Columns=3,Margin=new Thickness(-4,0,-4,10)};stats.Children.Add(Stat("筛选结果",FilterCount));stats.Children.Add(Stat("收支合计",FilterMoney));stats.Children.Add(Stat("未结资金",OpenFunds));stack.Children.Add(stats);stack.Children.Add(old);RecordsPage.Children.Add(stack);}
 static Border Stat(string title,TextBlock value){value.Text="—";value.FontSize=16;value.FontWeight=FontWeights.SemiBold;value.Margin=new Thickness(0,6,0,0);return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(12),Margin=new Thickness(4),Padding=new Thickness(14),Child=new StackPanel{Children={new TextBlock{Text=title,Foreground=(Brush)new BrushConverter().ConvertFromString("#7A8881")!},value}}};}
 void Load(){try{Directory.CreateDirectory(dir);if(File.Exists(FileName))data=JsonSerializer.Deserialize<LedgerData>(File.ReadAllText(FileName))??new();}catch{data=new();}}void Save(){Directory.CreateDirectory(dir);File.WriteAllText(FileName,JsonSerializer.Serialize(data,new JsonSerializerOptions{WriteIndented=true}));}static string M(decimal n)=>n.ToString("C2",new CultureInfo("zh-CN"));
 void Refresh(){var m=data.Records.Where(x=>x.Date.Year==DateTime.Today.Year&&x.Date.Month==DateTime.Today.Month);var inc=m.Where(x=>x.Type=="收入").Sum(x=>x.Amount);var exp=m.Where(x=>x.Type=="支出").Sum(x=>x.Amount);Income.Text=M(inc);Expense.Text=M(exp);Balance.Text=M(inc-exp);Outstanding.Text=M(data.Records.Where(x=>x.Status!="已结清"&&(x.Type=="借出"||x.Type=="投资中")).Sum(x=>x.Remaining));RecentList.ItemsSource=data.Records.OrderByDescending(x=>x.Date).Take(7).Select(x=>new EntryCardView{Entry=x});ApplyFilter();}
 void ApplyFilter(){if(!IsLoaded)return;var q=Search.Text.Trim();var t=TypeFilter.SelectedItem?.ToString();var raw=data.Records.Where(x=>(t is null or "全部类型"||x.Type==t)&&(q.Length==0||x.Category.Contains(q,StringComparison.OrdinalIgnoreCase)||x.Note.Contains(q,StringComparison.OrdinalIgnoreCase)||x.Party.Contains(q,StringComparison.OrdinalIgnoreCase))).OrderByDescending(x=>x.Date).ToList();EntryList.ItemsSource=raw.Select(x=>new EntryCardView{Entry=x});FilterCount.Text=$"{raw.Count} 笔账目";CountText.Text=$"共 {raw.Count} 笔";FilterMoney.Text=M(raw.Where(x=>x.Type=="收入").Sum(x=>x.Amount)-raw.Where(x=>x.Type=="支出").Sum(x=>x.Amount));OpenFunds.Text=M(raw.Where(x=>x.Status!="已结清"&&(x.Type=="借入"||x.Type=="借出"||x.Type=="投资中")).Sum(x=>x.Remaining));}
 void Add_Click(object s,RoutedEventArgs e){var d=new EntryDialogPro(data.Categories){Owner=this};if(d.ShowDialog()==true){data.Records.Add(d.Result);Save();Refresh();}}void OpenEntry_Click(object s,RoutedEventArgs e){if((s as FrameworkElement)?.DataContext is not EntryCardView vm)return;var d=new EntryDetailWindow(vm.Entry){Owner=this};d.ShowDialog();if(d.DeleteRequested){data.Records.RemoveAll(x=>x.Id==vm.Entry.Id);Save();Refresh();}else if(d.EditRequested){var edit=new EntryDialogPro(data.Categories,vm.Entry){Owner=this};if(edit.ShowDialog()==true){var i=data.Records.FindIndex(x=>x.Id==vm.Entry.Id);data.Records[i]=edit.Result;Save();Refresh();}}}
 void Show(UIElement p,string t){DashboardPage.Visibility=RecordsPage.Visibility=SettingsPage.Visibility=Visibility.Collapsed;p.Visibility=Visibility.Visible;PageTitle.Text=t;}void Dashboard_Click(object s,RoutedEventArgs e)=>Show(DashboardPage,"今天也要认真生活");void Records_Click(object s,RoutedEventArgs e)=>Show(RecordsPage,"明细账本");void Settings_Click(object s,RoutedEventArgs e)=>Show(SettingsPage,"数据与隐私");void Filter_Changed(object s,EventArgs e)=>ApplyFilter();void Title_Drag(object s,MouseButtonEventArgs e){if(e.ClickCount==2){Max_Click(s,e);return;}if(e.ChangedButton==MouseButton.Left)DragMove();}void Min_Click(object s,RoutedEventArgs e)=>WindowState=WindowState.Minimized;void Max_Click(object s,RoutedEventArgs e)=>WindowState=WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;void Close_Click(object s,RoutedEventArgs e)=>Close();
 void Backup_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="JSON 备份|*.json",FileName=$"简账备份-{DateTime.Today:yyyy-MM-dd}.json"};if(d.ShowDialog()==true)File.Copy(FileName,d.FileName,true);}void Restore_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="JSON 备份|*.json"};if(d.ShowDialog()==true)try{var x=JsonSerializer.Deserialize<LedgerData>(File.ReadAllText(d.FileName));if(x!=null){data=x;Save();Refresh();}}catch{MessageBox.Show("备份文件格式不正确。","简账");}}static string Q(string? s)=>$"\"{(s??"").Replace("\"","\"\"")}\"";void Csv_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="CSV 文件|*.csv",FileName=$"简账明细-{DateTime.Today:yyyy-MM-dd}.csv"};if(d.ShowDialog()==true){var b=new StringBuilder("日期,类型,金额,分类,账户,对象,状态,备注\r\n");foreach(var x in data.Records)b.AppendLine(string.Join(',',Q(x.Date.ToString("yyyy-MM-dd")),Q(x.Type),x.Amount,Q(x.Category),Q(x.Account),Q(x.Party),Q(x.Status),Q(x.Note)));File.WriteAllText(d.FileName,b.ToString(),new UTF8Encoding(true));}}
}
